import { Source_Code_Pro } from 'next/font/google'
import './globals.css'

const mono = Source_Code_Pro({ weight: ['500', '700'], subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={mono.className}>{children}</body>
    </html>
  )
}
